### ISSUE TITLE
video capture is running fine but not image loading frames from ip camera mobile app into webui project

### ISSUE THREAD

**Issue by RavindraProxce** [aws-samples/amazon-rekognition-video-analyzer#28]
Manage to do it 80% but frames which are captured is not showing in sample web ui project may be thinking frame from enrichframe api returining [] empty array object check if anybody can help on this.

**Comment by RavindraProxce** [comment]
it is uploading data to frame stream but not sure what is happening after this.

**Comment by moanany** [comment]
@RavindraProxce 

Here are a few places you can check for abnormalities:

1) AWS Lambda function logs (Image Processor and Frame Fetcher). Make sure there are no errors, and if there are, please post them here.

2) Check the EnrichedFrame DynamoDB table for image metadata. If there isn't any, that means frames are not getting past the Image Processor lambda function.

3) Check your browser's debugging tools. If the Web UI is having trouble receiving images, this could show up in the logs. Please post the errors here if there are any.

**Comment by ashishanand3413** [comment]
No metadata in the table. Frames are not getting past the image processor lambda function. What should I do to fix this issue?
