### ISSUE TITLE
createstack issue

### ISSUE THREAD

**Issue by RavindraProxce** [aws-samples/amazon-rekognition-video-analyzer#29]
some time it create stack and some time it's fails. there is any way so that on first command run (pynt createstack) it can create a stack in cloud formation.

**Comment by moanany** [comment]
Hey Ravindra -- what resources in the CloudFormation template is failing to create? Can you find out in the CloudFormation console and share the details?

**Comment by moanany** [comment]
The following section in the Amazon Rekognition docs provide guidance:

https://docs.aws.amazon.com/rekognition/latest/dg/faces.html

Thanks!

**Comment by RavindraProxce** [comment]
Yes issue not came back. You can close it.

Regards,
Ravindra Gorana
Technical Lead, Proxce, Inc.
ravindra@proxce.com
+917568039096
www.proxce.com<http://<br/>www.proxce.com>
https://in.linkedin.com/in/ravindra-gorana-3a724b34

________________________________
