### ISSUE TITLE
deploylambda error: Invalid stage identifier specified

### ISSUE THREAD

**Issue by pabloheimplatz** [aws-samples/amazon-rekognition-video-analyzer#30]
Hi,

I got an error while deploying my CloudFormation Script.

> botocore.exceptions.WaiterError: Waiter StackCreateComplete failed: Waiter encountered a terminal failure state

The Issue is somewhere around the `VidAnalyzerApiKey` scope, because I got this error:
`CREATE_FAILED | AWS::ApiGateway::ApiKey | VidAnalyzerApiKey | Invalid stage identifier specified`

Any ideas on this?
![screen shot 2018-04-24 at 14 15 10](https://user-images.githubusercontent.com/2726348/39186266-2afe9c2a-47ca-11e8-9930-db604935cfee.png)

**Comment by pabloheimplatz** [comment]
just deleted my cloudFormation script and restarted it. However it works now... Sorry!

**Comment by moanany** [comment]
Hello Pablo, 

It seems that there is some sort of a race condition that causes this issue to sometimes happen and sometimes not. I've added a dependency from VidAnalyzerApiKey to DevStage in the cloudformation script to solve this. From a few rounds of testing, the change seems to have mitigated the issue. Get the latest commit, and let me know if it happens again.

Thanks!

**Comment by pabloheimplatz** [comment]
Thanks for your feedback and for your fix! I think that will help so thanks a lot for your fast answer.
