### ISSUE TITLE
Where do Lambda Functions print to?

### ISSUE THREAD

**Issue by jaweiss8** [aws-samples/amazon-rekognition-video-analyzer#34]
I'm curious to see the content of the Rekognition JSON response.  I've noticed that there are a few print statements in imageprocessor.py--where do these print to?  For example line 146:
print("Successfully published alert message to SNS.")
Where can I see this output?

If I know the location, I can simply print out the contents of the Rekognition response.

**Comment by moanany** [comment]
Hello,

The logging statements are streamed into CloudWatch logs for the particular lambda function. More details here: https://docs.aws.amazon.com/lambda/latest/dg/python-logging.html#python-logging-finding-logs

Thanks,
Moataz
