### ISSUE TITLE
Invalid parameter: TopicArn Reason: An ARN must have at least 6 elements, not 1

### ISSUE THREAD

**Issue by danielblengino** [aws-samples/amazon-rekognition-video-analyzer#41]
I successfully built the entire project and run several times and it worked on an ipcam. Then, I started to insert some elements in the code to time the differents stages and now the video flux doesn't show up in the web ui. 

I have checked the logs of lambda functions, and the bug seems to come from imageprocessor. Indeed, this is what I get when i run the script on my built-in webcam :  

 07:18:01 On 09/19/18, 9:18 AM CEST...
 07:18:01 - "Human" was detected with 98.52% confidence.
 07:18:02 An error occurred (InvalidParameter) when calling the Publish operation: Invalid parameter: **TopicArn Reason: An ARN must have at least 6 elements, not 1**: InvalidParameterException Traceback (most recent call last): File "/var/task/imageprocessor.py", line 176, in handler return process_image(event, context) File "/var/task/imageprocessor.py", line 138, in process_image "labels": labels
 07:18:02 END RequestId: a33af59c...

So I tried to remove the phone number and arn topic in the image-processor-params.json, rebuild the entire project multiple times (deletedata, package lambda, deploylambda, updatestack, webui, webuiserver), tried also updatelambda command but it still doesn't work and I don't understand why.

Please help!

**Comment by fishercoder1534** [comment]
I'm faced w/ the exact same error, any insight would be appreciated!

**Comment by wilson-burea** [comment]
I'm having the same issue!

**Comment by fishercoder1534** [comment]
Well, the fix is simply to use the full qualified name of the ARN (e.g. `arn:aws:sns:us-east-1:123408653281:YOUR-SQS-NAME`) instead of a short name (e.g. `YOUR-SQS-NAME`).

**Comment by deepslama** [comment]
Couldn't delete subscription.
Error code: InvalidParameter - Error message: Invalid parameter: SubscriptionArn Reason: An ARN must have at least 6 elements, not 1


I am getting the above error, i had created topic and subscription, I deleted the topic before the subscription was deleted, i now have 1 Subscription  which is showing deleted but dose not disappear from the subscription. when I tried to delete i am getting the error above.

**Comment by deepslama** [comment]
Please help, i am new in aws learning

**Comment by MiguelPreto** [comment]
same

**Comment by 13AMohit** [comment]
simply use the "arn:aws:sns:ap-south-1:577573027390:[topicname]" change it according to your services

**Comment by zzmohammed** [comment]
that means you need to create topic first and then subscription, if topic is not there, subscription wont work
