### ISSUE TITLE
'JobStatus': 'FAILED', 'StatusMessage': 'Unsupported codec/format.'

### ISSUE THREAD

**Issue by zebpaypeswani** [aws-samples/amazon-rekognition-video-analyzer#46]
Hi I am able to search matched faces in a video. But sometimes I get above error. The error comes when the video format is not supported by `aws recognition`.
When I get that video from an android phone it works but if I get that video from other sources like web then it throw the error. 

I want to know how can I convert any video(whatever the source) to the aws supported video using ffmpeg 
Thanks

**Comment by jigs4444** [comment]
Hi , I have faced this issue too. How did you solve it?
